[package]
name = "imgui-vulkan-renderer-rs"
description = "Vulkan renderer for imgui-glfw-rs"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
imgui = "0.12.0"
ash = "0.38"
